# Generated by Django 4.0.4 on 2022-05-05 21:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_arquivo_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='arquivo_final',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='categoria',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('D', 'Design'), ('EV', 'Edição de Vídeo')], default='D', max_length=4),
        ),
    ]
